
cosmological:
  wc:
    value: 0.12
    prior: [0.085, 0.155]
    prior_type: uniform
    fixed: false
    latex: '\omega_c'
  
  wb:
    value: 0.022
    prior: [0.0205, 0.02415]
    prior_type: uniform
    fixed: false
    latex: '\omega_b'
  
  h:
    value: 0.67
    prior: [0.55, 0.85]
    prior_type: uniform
    fixed: false
    latex: 'h'
  
  ns:
    value: 0.965
    prior: [0.92, 1.01]
    prior_type: uniform
    fixed: false
    latex: 'n_s'
  
  As:
    value: 2.1
    prior: [1., 3.]
    prior_type: uniform
    fixed: false
    latex: '10^9 A_s'
  
  Mnu:
    value: 0.0
    prior: [0.0, 0.5]
    prior_type: uniform
    fixed: true
    latex: '\sum m_\nu'
  
  w0:
    value: -1.0
    prior: [-2.0, -0.33]
    prior_type: uniform
    fixed: true
    latex: 'w_0'
  
  wa:
    value: 0.0
    prior: [-2.0, 2.0]
    prior_type: uniform
    fixed: true
    latex: 'w_a'
  
  Ok:
    value: 0.0
    prior: [-0.1, 0.1]
    prior_type: uniform
    fixed: true
    latex: '\Omega_k'

bias:
  EggScoSmi:
    b1:
      value: 1.0
      prior: [0.5, 4.0]
      prior_type: uniform
      fixed: false
      latex: 'b_1'
    
    b2:
      value: 0.0
      prior: [-2.0, 2.0]
      prior_type: uniform
      fixed: false
      latex: 'b_2'
    
    g2:
      value: 0.0
      prior: [-5.0, 5.0]
      prior_type: uniform
      fixed: true
      latex: '\gamma_2'
    
    g21:
      value: 0.0
      prior: [-5.0, 5.0]
      prior_type: uniform
      fixed: true
      latex: '\gamma_{21}'
  
  AssBauGre:
    b1:
      value: 1.0
      prior: [0.5, 4.0]
      prior_type: uniform
      fixed: false
      latex: 'b_1'
    
    b2:
      value: 0.0
      prior: [-2.0, 2.0]
      prior_type: uniform
      fixed: false
      latex: 'b_2'
    
    bG2:
      value: 0.0
      prior: [-5.0, 5.0]
      prior_type: uniform
      fixed: true
      latex: 'b_{G_{2}}'
    
    bGam3:
      value: 0.0
      prior: [-5.0, 5.0]
      prior_type: uniform
      fixed: true
      latex: 'b_{\Gamma_{3}}'
  
  DESI:
    b1:
      value: 1.0
      prior: [0.1, 8.0]
      prior_type: uniform
      fixed: false
      latex: 'b_1'
    
    b2d:
      value: 0.0
      prior: [0, 20]
      prior_type: gaussian
      fixed: false
      latex: 'b_2'
    
    bk2:
      value: 0.0
      prior: [0, 20]
      prior_type: gaussian
      fixed: false
      latex: 'b_{K^2}'
    
    btd:
      value: 0.0
      prior: [0, 80]
      prior_type: gaussian
      fixed: false
      latex: 'b_{\rm td}'

counterterms:
  Comet:
    c0:
      value: 0.0
      prior: [-10000, 10000]
      prior_type: uniform
      fixed: true
      latex: 'c_0'
    
    c2:
      value: 0.0
      prior: [-10000, 10000]
      prior_type: uniform
      fixed: true
      latex: 'c_2'
    
    c4:
      value: 0.0
      prior: [-10000, 10000]
      prior_type: uniform
      fixed: true
      latex: 'c_4'
  
  DESIct:
    a0:
      value: 0.0
      prior: [-10000, 10000]
      prior_type: uniform
      fixed: true
      latex: '\alpha_0'
    
    a2:
      value: 0.0
      prior: [-10000, 10000]
      prior_type: uniform
      fixed: true
      latex: '\alpha_2'
    
    a4:
      value: 0.0
      prior: [-10000, 10000]
      prior_type: uniform
      fixed: true
      latex: '\alpha_4'

extra:
  VDG_infty:
    avir:
      value: 5.0
      prior: [0.0, 10.0]
      prior_type: uniform
      fixed: true
      latex: 'a_{\rm vir}'
  
  EFT:
    cnlo:
      value: 0.0
      prior: [0.0, 10.0]
      prior_type: gaussian
      fixed: true
      latex: 'c_{\rm nlo}'

stochastic:
  NP0:
    value: 0.0
    prior: [-1., 3.]
    prior_type: uniform
    fixed: true
    latex: 'N^P_0'
  
  NP20:
    value: 0.0
    prior: [-10000, 10000]
    prior_type: uniform
    fixed: true
    latex: 'N^P_{2,0}'
  
  NP22:
    value: 0.0
    prior: [-10000, 10000]
    prior_type: uniform
    fixed: true
    latex: 'N^P_{2,2}'
  
  NB0:
    value: 0.0
    prior: [-1., 3.]
    prior_type: uniform
    fixed: true
    latex: 'N^B_0'
  
  MB0:
    value: 0.0
    prior: [-3., 3.]
    prior_type: uniform
    fixed: true
    latex: 'M^B_0'

